---
driver: 
  name: vagrant

provisioner:
  name: chef_solo

platforms:
- driver: {boot_timeout: 600, box: shrey/centos65}
  name: centos-6.5

suites:
  - name: default
    run_list:
      - recipe[git::default]
    attributes:
